### ISSUE TITLE
Chess demo - can I reimplement it?

### ISSUE THREAD

**Issue by brucou** [raulsebastianmihaila/crizmas-mvc#1]
Hola Raul,

I am interested in rewriting the [chess game](https://raulsebastianmihaila.github.io/chess/) using [state machines](https://github.com/brucou/state-transducer) to control the UI. As I see that the application is under copyright, I wanted to ask your permission to do so. I obviously will not sell in any ways the resulting application and credit will be given to you for authoring the original application. I would however like to reuse the interface (css, chess pieces, etc.). I intend this to be more a demo for the use of state machines for controlling user interfaces. 

I found crizmas-mvc from the `real-world` repo and I have been intrigued by it. I think that having a controller driving the interface gives for a much more sound architecture, instead of having what should be mere view libraries turning into full ui framework as they concern themselves with controlling the application (like synchronizing state and effects with the component lifecycle).

I already wanted to implement a chess game because it is relatively easy. There are a number of MIT-licenses implementation out there, but yours is one I found most attractive. But mostly it will be much easier to compare controller-based architecture to controller-based architecture and see what is gained and what is lost with state machines.

Once that is done, I will probably write some article about it (where the original implementation will be credited and linked to), and add a demo link on my github repository. Let me know if that works for you. In any case, kudo for returning to controllers as the central piece for orchestrating user interfaces.

**Comment by brucou** [comment]
no answer, so closing this, I picked up [another chess implementation](https://brucou.github.io/documentation/v1/tutorials/chess-game-ultimate.html) in the end.

**Comment by raulsebastianmihaila** [comment]
Hi @brucou,

Sorry for responding so late, I didn't get any notification related to this issue, it seems that by default Github doesn't notify you about your own repos, I updated my settings. Perhaps it is safer to mention the user in the comment in order to make sure that they will be notified.

I'm glad you found another implementation. Since it's 'relatively easy', I guess you could have built one yourself. :) I wouldn't necessarily say that controllers are the **central** piece in MVC, but they are definitely very important.

I was curious about a comparison between approaches, but more regarding a real world application, not a game. Did you consider using your approach on the `real-world` repo that you mentioned? I took a quick look at your [link](https://brucou.github.io/documentation/v1/tutorials/chess-game-evolved.html#Comparing-with-a-non-state-machine-implementation) and saw you wrote a few words about why the **standard techniques** are a worse approach, in the `handleClick` example. I guess that by 'standard techniques' you're referring to what you mentioned in your previous message, namely controlling an application from the view layer. If you could do your implementation of the real world application and compare it to the `crizmas-mvc` approach, it would be awesome!

**Comment by brucou** [comment]
Hi raul, or should I say @raulsebastianmihaila 

thanks for the advice, I don't know much about github notification arcane stuff either. But it is good to know.

I was saying that Implementing a chess game is relatively easy, because it is a pretty studied game, and lots of libraries exist which you can reuse. Writing it from scratch could be a challenge, but patching up libraries makes it better. I was interested in the chess game to showcase [Kingly](https://brucou.github.io/documentation), my state machine library for specifying and implementing user interfaces. It comes pretty short as I reuse a chess engine and a chess React component. I basically only implemented the logic, not of the game, but of the interface. And that is relatively easy as I said. I see that you actually reviewed the implementation (I am impressed, not many people are interested in state machines). So you can see that there aren't many states in that state machine. And that is the point, if you safely separate things, a chess engine for the chess game and rules, a chess React component for displaying the game, and a chess controller for driving the UI, then you can reuse the separate parts, well, separately. 

What I refer by standard techniques, I refer to two things. First if `if then else` control flow which does not scale with the complexity of the logic you want to implement. Second, complecting the UI behaviour (the chess state machine) with the UI representation (the chess React component). I am not sure about terminology but I believe what I call UI behaviour might be termed application logic in the [DDD layered architecture](http://uniknow.github.io/AgileDev/site/0.1.9-SNAPSHOT/parent/ddd/core/images/LayersAndDDD.png).

And that's funny I was actually thinking about RealWorld two weeks ago. I will get to it, again if I can reuse a ton of things (css, backend implementation, etc.) so I don't have to spend too much time on it. Right now, I provided [functionality similar to React Suspense](https://brucou.github.io/documentation/v1/examples/svelte%20suspense.html) with the Svelte framework. Next I will write about routing with state machines. Then RealWorld app. Lots of stuff which is why I always try to enrich existing applications rather than redo stuff.

Thanks for your answer! It is nice to see that you took the time to read the article. I will let you know when I get to the realworld example!

**Comment by brucou** [comment]
@raulsebastianmihaila
So, it took forever, but I got an implementation of the Conduit demo app here: https://rw-kingly-svelte.bricoi1.now.sh/. Repo is this one: https://github.com/brucou/realworld-kingly-svelte.

This is the first working draft (make it work step). I will spend some time (later) in the make it right step. I have it bundled at 39 KB which is ok I guess, but ideally I would like to get closer to Elm (30KB). Performance-wise, it gets a 95 score on LightHouse audit, so that is quite acceptable.

I will try to write down the learnings and conclusions from the experience. For now, a step-by-step tutorial is available: https://brucou.github.io/documentation/v1/tutorials/real-world.html
